lib/self_web/router.ex
defmodule SelfWeb.Router do
  use SelfWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SelfWeb.Plug.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SelfWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/paises", PaisController
    resources "/estados", EstadoController
    resources "/cidades", CidadeController
    resources "/enderecos", EnderecoController
    resources "/clientes", ClienteController
    resources "/fornecedores", FornecedorController
    resources "/funcionarios", FuncionarioController
    resources "/produtos", ProdutoController
    resources "/compras", CompraController
    resources "/itens_compra", ItemCompraController
    resources "/vendas", VendaController
    resources "/itens_venda", ItemVendaController
    resources "/usuarios", UsuarioController
    get "/itens_venda/:id/venda", ItemVendaController, :venda
    get "/itens_compra/:id/compra", ItemCompraController, :compra
  end

  scope "/auth", SelfWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    get "/:provider/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", SelfWeb do
  #   pipe_through :api
  # end
end

lib/self_web/views/layout_view.ex
defmodule SelfWeb.LayoutView do
  use SelfWeb, :view
end

lib/self_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" href="https://raw.githubusercontent.com/ebasantos/estoque-web-app-front-end/master/src/img/self%20stock.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Self Stock WEB</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
      <nav class="row">
        <div class="col-10">
          <section class="menu menu--circle ">
            <input type="checkbox" id="menu__active"/>
            <label for="menu__active" class="menu__active">
              <div class="menu__toggle">
                <div class="icon">
                  <div class="hamburger"></div>
                </div>
              </div>
              <input type="radio" name="arrow--up" id="degree--up-0"/>
              <input type="radio" name="arrow--up" id="degree--up-1" />
              <input type="radio" name="arrow--up" id="degree--up-2" />
              <div class="menu__listings">
                
                <ul class="circle">   
                  
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                         <a href="/clientes" class="button"><i class="fas fa-address-book"></i></a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                         <a href="/produtos" class="button"><i class="fas fa-box"></i></a>
                      </div>
                    </div>
                  </li>
                  
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/produtos" class="button"><i class="fas fa-box"></i></a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/vendas" class="button"><i class="fas fa-cash-register"></i></a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/compras" class="button"><i class="fas fa-shopping-cart"></i></a>
                      </div>
                    </div>
                  </li>    
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/fornecedores" class="button"><i class="fas fa-hands-helping"></i></a>
                      </div>
                    </div>
                  </li>      
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/paises" class="button"><i class="fas fa-globe-americas"></i></a>
                      </div>
                    </div>
                  </li>            
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/estados" class="button"><i class="fas fa-flag"></i></a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="placeholder">
                      <div class="upside">
                        <a href="/cidades" class="button"><i class="fas fa-city"></i></a>
                      </div>
                    </div>
                  </li>
                   <li>
                    <div class="placeholder">
                      <div class="upside">
                          <a href="/enderecos" class="button"><i class="fas fa-map-marked-alt"></i></a>
                      </div>
                    </div>
                  </li>     
                </ul>
              </div>
              <div class="menu__arrow menu__arrow--top">
                <ul>
                  <li>
                    <label for="degree--up-0"><div class="arrow"></div></label>
                    <label for="degree--up-1"><div class="arrow"></div></label>
                    <label for="degree--up-2"><div class="arrow"></div></label>
                  </li>
                </ul>
              </div>
            </label>
        </section>
      </div>
      <div class="nav-wrapper container">
        <a href="#" class="brand-logo"></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
              <%= if @conn.assigns[:user] do %>
                <li  class="col-6 ">  
                  <a href="<%= Routes.auth_path(@conn, :logout, "facebook") %>">
                    <i class="fas fa-sign-out-alt"></i> 
                  </a> 
                </li>
                <li class="col-6">
                    <div class="placeholder">
                      <div class="upside">
                        <%= link  to: Routes.usuario_path(@conn, :index)  do  %>
                          <i class="fas fa-user-plus"></i>
                        <%= end %>
                      </div>
                    </div>
                  </li>
              <%= else %>
                <li class="col-3">
                      <a  href="<%= Routes.auth_path(@conn, :request, "facebook") %>">
                          <i class="fab fa-facebook">
                          </i>
                      </a>
                </li  >  
                <li class="col-3" >  
                  <a  href="<%= Routes.auth_path(@conn, :request, "github") %>" >
                    <i class="fab fa-github-alt">
                    </i>
                  </a>     
                </li  >  
              <%= end %>
        </ul>
      </div>
  </nav>
  </head>

  <body>
     <main role="main" class="container">
        <div class="row">
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
            <%= render @view_module, @view_template, assigns %>
        </div>
    </main>
    <footer id="contact" class="footer">             
                                    <div class="widget_brand m-top-40 col-md-12"  style='text-align: center'>
                                        <a href="/" class="text-uppercase"><img class="img-thumbnail" src="https://raw.githubusercontent.com/ebasantos/estoque-web-app-front-end/master/src/img/self%20stock.png" class="img-thumbnail"  style='background-color: transparent; width: 100px;' alt="Self-Stock-WEB" />
                                        </a>
                                        <p class="text-white">A melhor solução em controle de estoque!</p>
                                    </div>
                                </div>                          
                <div class="main_footer fix bg-mega text-center">
                    <div class="col-md-12">
                        <p class="wow fadeInRight text-white" data-wow-duration="1s">
                            <i class="fa fa-phone"></i> 
                            2019. All Rights Reserved
                        </p>
                    </div>
                </div>
      </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>