lib/self_web/router.ex
defmodule SelfWeb.Router do
  use SelfWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SelfWeb.Plug.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SelfWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/paises", PaisController
    resources "/estados", EstadoController
    resources "/cidades", CidadeController
    resources "/enderecos", EnderecoController
    resources "/clientes", ClienteController
    resources "/fornecedores", FornecedorController
    resources "/funcionarios", FuncionarioController
    resources "/produtos", ProdutoController
    resources "/compras", CompraController
    resources "/itens_compra", ItemCompraController
    resources "/vendas", VendaController
    resources "/itens_venda", ItemVendaController
    resources "/usuarios", UsuarioController
    get "/itens_venda/:id/venda", ItemVendaController, :venda
    get "/itens_compra/:id/compra", ItemCompraController, :compra
  end

  scope "/auth", SelfWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    get "/:provider/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", SelfWeb do
  #   pipe_through :api
  # end
end

lib/self/movimentacao/venda.ex
defmodule Self.Movimentacao.Venda do
  use Ecto.Schema
  import Ecto.Changeset

  schema "vendas" do
    field :data, :date
    field :desconto, :decimal
    field :valor, :decimal
    field :funcionario_id, :id
    field :cliente_id, :id

    timestamps()
  end

  @doc false
  def changeset(venda, attrs) do
    venda
    |> cast(attrs, [:valor, :data, :desconto, :funcionario_id, :cliente_id])
    |> validate_required([:data, :desconto, :funcionario_id, :cliente_id])
  end
end

lib/self_web/controllers/venda_controller.ex
defmodule SelfWeb.VendaController do
  use SelfWeb, :controller

  alias Self.Movimentacao
  alias Self.Movimentacao.Venda

  plug SelfWeb.Plug.RequireAuth when action in [:index, :edit, :new, :show, :create, :update, :delete]

  def index(conn, _params) do
    vendas = Movimentacao.list_vendas()
    render(conn, "index.html", vendas: vendas)
  end

  def new(conn, _params) do
    changeset = Movimentacao.change_venda(%Venda{})
    funcionarios = Self.Ator.select_funcionarios
    clientes = Self.Ator.select_clientes
    render(conn, "new.html", changeset: changeset, funcionarios: funcionarios, clientes: clientes)
  end

  def create(conn, %{"venda" => venda_params}) do
    case Movimentacao.create_venda(venda_params) do
      {:ok, venda} ->
        conn
        |> put_flash(:info, "Venda criado com sucesso.")
        |> redirect(to: Routes.venda_path(conn, :show, venda))

      {:error, %Ecto.Changeset{} = changeset} ->
        funcionarios = Self.Ator.select_funcionarios
        clientes = Self.Ator.select_clientes
        render(conn, "new.html", changeset: changeset, funcionarios: funcionarios, clientes: clientes)
    end
  end

  def show(conn, %{"id" => id}) do
    venda = Movimentacao.get_venda!(id)
    render(conn, "show.html", venda: venda)
  end

  def edit(conn, %{"id" => id}) do
    venda = Movimentacao.get_venda!(id)
    changeset = Movimentacao.change_venda(venda)
    funcionarios = Self.Ator.select_funcionarios
    clientes = Self.Ator.select_clientes
    render(conn, "edit.html", venda: venda, changeset: changeset, funcionarios: funcionarios, clientes: clientes)
  end

  def update(conn, %{"id" => id, "venda" => venda_params}) do
    venda = Movimentacao.get_venda!(id)

    case Movimentacao.update_venda(venda, venda_params) do
      {:ok, venda} ->
        conn
        |> put_flash(:info, "Venda atualizado com sucesso.")
        |> redirect(to: Routes.venda_path(conn, :show, venda))

      {:error, %Ecto.Changeset{} = changeset} ->
        funcionarios = Self.Ator.select_funcionarios
        clientes = Self.Ator.select_clientes
        render(conn, "edit.html", venda: venda, changeset: changeset, funcionarios: funcionarios, clientes: clientes)
    end
  end

  def delete(conn, %{"id" => id}) do
    venda = Movimentacao.get_venda!(id)
    {:ok, _venda} = Movimentacao.delete_venda(venda)

    conn
    |> put_flash(:info, "Venda excluido com sucesso.")
    |> redirect(to: Routes.venda_path(conn, :index))
  end

end

lib/self_web/views/venda_view.ex
defmodule SelfWeb.VendaView do
  use SelfWeb, :view
end

lib/self_web/templates/venda/edit.html.eex
<div class="default-form">
    <h1 class="h1">Alterar Venda</h1>

    <%= render "form.html", Map.put(assigns, :action, Routes.venda_path(@conn, :update, @venda)) %>

    <span><%= link "Voltar", to: Routes.venda_path(@conn, :index), class: "btn" %></span>
</div>

lib/self_web/templates/venda/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, algo deu errado! Por favor veja os erros abaixo.</p>      
    </div>
  <% end %>

  <%# <%= label f, :valor %>
  <%# <%= number_input f, :valor, step: "any" %>
  <%= error_tag f, :valor %>

  <%= label f, :data %>
  <%= date_input f, :data, class: "form-control" %>
  <%= error_tag f, :data %>

  <%= label f, :desconto %>
  <%= number_input f, :desconto, step: "any" %>
  <%= error_tag f, :desconto %>

  <%= label f, :funcionario_id %>
  <%= select f, :funcionario_id, @funcionarios, class: "form-control" %>
  <%= error_tag f, :funcionario_id %>

  <%= label f, :cliente_id %>
  <%= select f, :cliente_id, @clientes, class: "form-control" %>
  <%= error_tag f, :cliente_id %>
 
   
  <div>
    <%= submit "Salvar" %>
  </div>
<% end %>

lib/self_web/templates/venda/index.html.eex
<div class="default-form"> 
  <h1 class="h1">Vendas</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Valor</th>
        <th>Data</th>
        <th>Desconto</th>
        <th>Visualizar itens</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
  <%= for venda <- @vendas do %>
      <tr>
        <td><%= venda.valor %></td>
        <td><%= venda.data %></td>
        <td><%= venda.desconto %></td>
        <td>
          <%= link "Visualizar", to: Routes.venda_path(@conn, :show, venda), class: "btn" %>
          <%= link "Editar", to: Routes.venda_path(@conn, :edit, venda), class: "btn" %>
          <%= link "Excluir", to: Routes.venda_path(@conn, :delete, venda), method: :delete, data: [confirm: "Tem certeza?"], class: "btn" %>        
          <div class="placeholder">
            <div class="upside">
              <a href="<%= Routes.item_venda_path(@conn, :venda, venda) %>" class="btn"><i class="fas fa-shopping-cart"></i></a>
            </div>
          </div>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>

  <span><%= link "Nova Venda", to: Routes.venda_path(@conn, :new), class: "btn" %></span>
</div>

lib/self_web/templates/venda/new.html.eex
<div class="default-form"> 
    <h1 class="h1">Nova Venda</h1>

    <%= render "form.html", Map.put(assigns, :action, Routes.venda_path(@conn, :create)) %>

    <span><%= link "Voltar", to: Routes.venda_path(@conn, :index), class: "btn" %></span>
</div>

lib/self_web/templates/venda/show.html.eex
<div class="default-form">  
  <h1 class="h1">Visualizar Venda</h1>

  <ul>

    <li>
      <strong>Valor:</strong>
      <%= @venda.valor %>
    </li>

    <li>
      <strong>Data:</strong>
      <%= @venda.data %>
    </li>

    <li>
      <strong>Desconto:</strong>
      <%= @venda.desconto %>
    </li>
    <li>
        <span><%= link "Alterar", to: Routes.venda_path(@conn, :edit, @venda), class: "btn" %></span>
    </li>
    <li>
        <span><%= link "Voltar", to: Routes.venda_path(@conn, :index), class: "btn" %></span>
    </li>
  </ul>



</div>